version: '3.8'

services:
    database:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mpw_bicycle_challenge
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - '3306:3306'
    php:
        build:
            context: ./php
        volumes:
            - ./app:/app
        depends_on:
            - database
    web:
        image: nginx
        ports:
            - '8080:80'
        volumes:
            - ./app:/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php